spring:
  config:
    activate:
      on-profile: dev
  boot:
    admin:
      client:
        url: http://platform-common-boot-admin-1525162385.ap-northeast-2.elb.amazonaws.com
      instance:
        prefer-ip: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://platform-dev-common.cptfqf0ipdzt.ap-northeast-2.rds.amazonaws.com:3306/edsdb?autoReconnect=true&connectTimeout=3000&socketTimeout=4500&allowMultiQueries=true&retriesAllDown=3
      username: root
      password: et53,!$l1)&
  redis:
    host: platform-dev-common.svru9h.clustercfg.apn2.cache.amazonaws.com
    port: 6379
    database: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

logging:
  level:
    com.zaxxer.hikari.HikariConfig: ERROR
    com.zaxxer.hikari: ERROR